### ISSUE TITLE
How to find the data files for all participants

### ISSUE THREAD

**Issue by GHarmata** [HBClab/xcpOut#3]
> files <- dir(pattern="sub-.*\\\_schaefer400_network.txt", all.files = T, recursive=T)

reference: https://stackoverflow.com/questions/10353540/listing-all-files-matching-a-full-path-pattern-in-r

**Comment by mwvoss** [comment]
below is solution we found for .net files that will then exclude *_network.txt files

`files <- dir(pattern="sub-.*\\_schaefer400\\.net", all.files = T, recursive=T)`
