### ISSUE TITLE
Possible for loop

### ISSUE THREAD

**Issue by GHarmata** [HBClab/xcpOut#4]
dummylist <- data.frame("subjects" = c("sub-BIKE202"))

    ##double backslash for regex to take stuff literally
    files <- dir(pattern="sub-.*\\_schaefer400\\.net", all.files = T, recursive=T)

    dummylist_data <- data.frame()

    for(i in dummylist$subjects){
        subjectid <- dummylist$subjects
        match <- grepl(x=files, pattern=subjectid)
        #https://stackoverflow.com/questions/14420936/error-in-filefile-rt-invalid-description-argument-in-complete-cases-pro
        whichfile <- files[match]
    
        sub_correlation_matrix_net <- read.table(whichfile, header=FALSE,sep=" ",skip=2)
        sub_correlation_matrix_net <- sub_correlation_matrix_net[,1:3]
        names(sub_correlation_matrix_net) <- c("roi1","roi2","fc") # give headers
        
        # uses lookup table and replaces number with that text
        sub_correlation_matrix_net$roi1_name <- schaefer_lut[match(sub_correlation_matrix_net$roi1,schaefer_lut$roi_index),"roi_label"]
        sub_correlation_matrix_net$roi2_name <- schaefer_lut[match(sub_correlation_matrix_net$roi2,schaefer_lut$roi_index),"roi_label"]
        
        # separate into diff variables
        sub_correlation_matrix_net <- sub_correlation_matrix_net %>%
            separate(col= roi1_name, sep="_", into = c("roi1_hemi", "roi1_subnetwork", "roi1_region", "roi1_regionindex")) 
        
        sub_correlation_matrix_net <- sub_correlation_matrix_net %>%
            separate(col= roi2_name, sep="_", into = c("roi2_hemi", "roi2_subnetwork", "roi2_region", "roi2_regionindex"))
        
        #roi1
        sub_correlation_matrix_net$roi1_regionindex <- if_else(
            is.na(sub_correlation_matrix_net$roi1_regionindex), 
            true= sub_correlation_matrix_net$roi1_region, 
            false = sub_correlation_matrix_net$roi1_regionindex)
        
        sub_correlation_matrix_net$roi1_region <- if_else(
            sub_correlation_matrix_net$roi1_region==sub_correlation_matrix_net$roi1_regionindex, 
            true="", 
            false = sub_correlation_matrix_net$roi1_region)
        
        # roi2
        
        sub_correlation_matrix_net$roi2_regionindex <- if_else(
            is.na(sub_correlation_matrix_net$roi2_regionindex), 
            true= sub_correlation_matrix_net$roi2_region, 
            false = sub_correlation_matrix_net$roi2_regionindex)
        
        sub_correlation_matrix_net$roi2_region <- if_else(
            sub_correlation_matrix_net$roi2_region==sub_correlation_matrix_net$roi2_regionindex, 
            true="", 
            false = sub_correlation_matrix_net$roi2_region)
        
        sub_correlation_matrix_net <- sub_correlation_matrix_net %>%
            mutate(subject_id= subjectid)
            
       dummylist_data <<- rbind(dummylist_data,sub_correlation_matrix_net)
    }

**Comment by mwvoss** [comment]
Update on solution with a text file subject list such as `fcon_sublist.txt`  with contents
sub-BIKE202
sub-BIKE206
sub-BIKE223
sub-BIKE225


loop:
```

# load sublist
subs <- read.table("fcon_sublist.txt",header=FALSE)
names(subs) <- c("subject_id")

# look in all files that match pattern 
files <- dir(pattern="sub-.*\\_schaefer400\\.net", all.files = T, recursive=T)

# create empty data frame to fill with subject data
fcon_df <- data.frame()

# for each subject in list, find+load+reformat variable names, concatenate all subjects with rbind
for (i in subs$subject_id){
     print(i)
        subject_id <- i
        match <- grepl(x=files, pattern=i)
        whichfile <- files[match]
        sub_correlation_matrix_net <- read.table(whichfile,header=FALSE,sep=" ",skip=2)
        sub_correlation_matrix_net <- sub_correlation_matrix_net[,1:3] 
        names(sub_correlation_matrix_net) <- c("roi1","roi2","fc") # give headers
        sub_correlation_matrix_net$subject_id <- i
        fcon_df <<- rbind(fcon_df,sub_correlation_matrix_net)
}
```

**Comment by mwvoss** [comment]
A new issue can tackle using a more efficient method in R that doesn't require looping
